### ISSUE TITLE
missing go.sum

### ISSUE THREAD

**Issue by JanLin** [cloudprivacylabs/lsa-neo4j#1]
Small issue. When running go build received an error message.

M:\lsaneo> go build
go: github.com/cloudprivacylabs/lsa@v1.0.0-beta6.0.20211026231431-ea4966946d6e requires
        github.com/bserdar/jsonom@v0.0.0-20211005020717-9af6d87a0e9f: missing go.sum entry; to add it:
        go mod download github.com/bserdar/jsonom

After running below command "go build" worked.
go mod download github.com/bserdar/jsonom

**Comment by bserdar** [comment]
Updated instructions to include `go mod tidy`
